spring:
  application:
    name: data_synchronizer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080
  compression:
    enabled: true
  error:
    include-message: always
com:
  meysamzamani:
    data_synchronizer:
      location: /files/
      storage:
        access_key: <YOUR_ACCESS_KEY>
        secret_key: <YOUR_SECRET_KEY>
        endpoint: s3-eu-central-1.ionoscloud.com
        region: us-east-1
        bucket: customer